server.port=9092
spring.application.name=TEAM-SERVICE

#database
spring.datasource.url=jdbc:mysql://localhost:3306/gullycricket
spring.datasource.username=root
spring.datasource.password=ashish@11


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
feign.okhttp.enabled=true